// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBtxhdCkU3Pu7ApaZs-vO01r-g6YFGkeV4',
//     appId: '1:602193694864:web:f43ac99be22553a4ce8815',
//     messagingSenderId: '602193694864',
//     projectId: 'app-starnotes',
//     authDomain: 'app-starnotes.firebaseapp.com',
//     storageBucket: 'app-starnotes.appspot.com',
//     measurementId: 'G-HH7DNKBHWT',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCgefvy9wcLDxyM3bygeEqkDpyv_83APZk',
//     appId: '1:602193694864:android:6d67ee24d9aad967ce8815',
//     messagingSenderId: '602193694864',
//     projectId: 'app-starnotes',
//     storageBucket: 'app-starnotes.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBxZkzDxOM4wC5V61_NfsYO7Pq4jMj7E4I',
//     appId: '1:602193694864:ios:53d80e9550e8fee6ce8815',
//     messagingSenderId: '602193694864',
//     projectId: 'app-starnotes',
//     storageBucket: 'app-starnotes.appspot.com',
//     iosClientId: '602193694864-p02s7rr8kodoodkf00d2u09mavqa2f5p.apps.googleusercontent.com',
//     iosBundleId: 'com.sincroneasy.starNotes',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBxZkzDxOM4wC5V61_NfsYO7Pq4jMj7E4I',
//     appId: '1:602193694864:ios:53d80e9550e8fee6ce8815',
//     messagingSenderId: '602193694864',
//     projectId: 'app-starnotes',
//     storageBucket: 'app-starnotes.appspot.com',
//     iosClientId: '602193694864-p02s7rr8kodoodkf00d2u09mavqa2f5p.apps.googleusercontent.com',
//     iosBundleId: 'com.sincroneasy.starNotes',
//   );
// }
